server:
  port: 2208
  servlet:
    context-path: /api/v1/my-notepad

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.default_schema: ${DB_DEFAULT_SCHEMA}
      jdbc:
        lob:
          non_contextual_creation: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: my-notepad
    version: v1

request-mapping:
  controller:
    category: category
    user: user
    note: note